# The container images used in this pipeline are built from this
# GitLab project: https://gitlab.gnome.org/sthursfield/tracker-oci-images/

stages:
  - test

test-fedora-latest:
  stage: test
  image: registry.gitlab.gnome.org/sthursfield/tracker-oci-images/amd64/fedora:latest

  script:
    # We can build and test tracker-miners against tracker just by building
    # tracker as a submodule.
    #
    # Note that this approach doesn't currently work for the functional-tests,
    # they require the ontologies and domain rules from tracker to be installed
    # somewhere. It would be nice to improve the functional-tests so that they
    # will run without depending on any files outside of the build tree. Note
    # that Tracker is installed on the host here, thanks to `dnf builddep`.
    - su tracker -c 'mkdir subprojects; cd subprojects; git clone https://gitlab.gnome.org/GNOME/tracker'
    - su tracker -c 'mkdir build'
    - su tracker -c 'cd build; meson .. --prefix=/usr -Dtracker_core=subproject'
    - su tracker -c 'cd build; ninja'
    - |
      # Remove the many "CI_" variables from the environment. Meson dumps the
      # whole environment for every failed test, and that gives a whole
      # screenful of junk each time unless we strip these.
      unset $(env|grep -o '^CI_[^=]*')

      su tracker -c 'cd build; dbus-run-session -- env LANG=en_US.UTF8 meson test --suite tracker-miners --print-errorlogs'
